import { defineField, defineType } from 'sanity';

export const product = defineType({
  name: 'product',
  title: 'Product (Jewelry Piece)',
  type: 'document',
  groups: [
    { name: 'main', title: 'Basics', default: true },
    { name: 'details', title: 'Details' },
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Name (Indonesian)',
      description: 'The product name shown on the Indonesian site.',
      type: 'string',
      group: 'main',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'nameEn',
      title: 'Name (English)',
      description: 'The name shown on the English site.',
      type: 'string',
      group: 'main',
    }),
    defineField({
      name: 'category',
      title: 'Category',
      description: 'Which collection this piece belongs to (Rings, Necklaces, …).',
      type: 'reference',
      to: [{ type: 'category' }],
      group: 'main',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'price',
      title: 'Price (Rupiah)',
      description: 'Numbers only, no dots. e.g. type 350000 to show Rp 350.000.',
      type: 'number',
      group: 'main',
      validation: (Rule) => Rule.required().min(0),
    }),
    defineField({
      name: 'images',
      title: 'Photos',
      description: 'The first photo is the main one. Add more for the product-page gallery. Drag to reorder.',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
      group: 'main',
    }),
    defineField({
      name: 'inStock',
      title: 'In stock?',
      description: 'Turn off to mark the piece as unavailable and hide the Add-to-Bag button.',
      type: 'boolean',
      initialValue: true,
      group: 'main',
    }),
    defineField({
      name: 'featured',
      title: 'Show on home page?',
      description: 'Featured pieces appear in the scrolling strip on the home page.',
      type: 'boolean',
      initialValue: false,
      group: 'main',
    }),

    defineField({
      name: 'description',
      title: 'Description (Indonesian)',
      description: 'Shown on the product page.',
      type: 'text',
      rows: 4,
      group: 'details',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'descriptionEn',
      title: 'Description (English)',
      type: 'text',
      rows: 4,
      group: 'details',
    }),
    defineField({
      name: 'material',
      title: 'Material',
      type: 'string',
      description: 'e.g. Perak 925 / 925 Sterling Silver.',
      group: 'details',
    }),
    defineField({
      name: 'sizes',
      title: 'Available sizes',
      type: 'string',
      description: 'Comma-separated. e.g. “6, 7, 8, 9” or “Free Size”. Leave blank if there are no sizes.',
      group: 'details',
    }),
    defineField({
      name: 'stone',
      title: 'Stone / gem',
      type: 'string',
      description: 'e.g. Blue Topaz, Onyx. Leave blank if none.',
      group: 'details',
    }),
    defineField({
      name: 'weight',
      title: 'Weight (grams)',
      type: 'number',
      group: 'details',
    }),
    defineField({
      name: 'craftingTime',
      title: 'Lead time',
      type: 'string',
      description: 'e.g. “3–5 hari kerja”.',
      group: 'details',
    }),
    defineField({
      name: 'isCustomizable',
      title: 'Can be customised?',
      type: 'boolean',
      initialValue: false,
      group: 'details',
    }),
    defineField({
      name: 'slug',
      title: 'Web address (automatic)',
      description: 'Part of the page link. Fills in from the name — click “Generate” after naming the piece; you rarely need to change it.',
      type: 'slug',
      options: { source: 'name', maxLength: 96 },
      group: 'details',
      validation: (Rule) => Rule.required(),
    }),
  ],
  preview: {
    select: { title: 'name', media: 'images.0', subtitle: 'price', stock: 'inStock' },
    prepare({ title, media, subtitle, stock }) {
      const price = subtitle ? `Rp ${subtitle.toLocaleString('id-ID')}` : 'No price';
      return { title, media, subtitle: stock === false ? `${price} · Out of stock` : price };
    },
  },
});
